# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Triggers
trigger:
- master

# Pools
pool:
  vmImage: 'ubuntu-latest'

# Steps
steps:

- script: echo Hello, ICT DevOps!
  displayName: 'Run a one-line script'

- script: |
    echo Let us add more tasks to build, test, and deploy our project.
    echo Learn more about YAML!
    echo noor
  displayName: 'Run a multi-line script'
