# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello,htu!
  displayName: 'Run a one-line script'

- script: bash build.sh
  displayName: 'Run build script'
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'lolo@40.117.249.24'
    sourceFolder: 'web/'
    contents: '**'
    targetFolder: '/var/www/html'
    cleanTargetFolder: true
    readyTimeout: '20000'
    failOnEmptySource: true
