# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello,htu!
  displayName: 'Run a one-line script'

- script: bash build.sh $(AZURE_VARIABLE) $(Build.SourceBranchName)
  displayName: 'Run build script'
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'lolo@40.117.249.24'
    sourceFolder: 'web/'
    contents: '**'
    targetFolder: '/var/www/html'
    readyTimeout: '20000'
    failOnEmptySource: true
- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'walaahijazi'
    repositoryName: 'walaahijazi/devops-ci-demo'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: '$(Build.BuildNumber)'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'



    